name: Generate and Upload Lab6 Report

on:
  push:
    branches:
      - main
    paths:
      - 'lab_06/**'
      - '.github/workflows/lab6_actions.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc inkscape texlive-xetex texlive-fonts-recommended texlive-latex-extra poppler-utils

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pint scipy matplotlib numpy nbconvert ipykernel

      - name: Convert Jupyter Notebook to PDF
        run: |
          jupyter nbconvert --to pdf --execute ./lab_06/lab6.ipynb --output-dir ./lab_06/

      - name: Run Pylint on notebook-converted script
        run: |
          jupyter nbconvert --to python ./lab_06/lab6.ipynb --output ./lab_06/lab6_script.py
          pylint ./lab_06/lab6_script.py > ./lab_06/pylint_report.txt || true

      - name: Convert Pylint report to PDF
        run: |
          pandoc ./lab_06/pylint_report.txt -o ./lab_06/pylint_report.pdf

      - name: Combine lab report PDF and Pylint report PDF
        run: |
          pdfunite ./lab_06/lab6.pdf ./lab_06/pylint_report.pdf ./lab_06/lab6_full.pdf

      - name: Commit PDFs to repository
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add ./lab_06/lab6.pdf ./lab_06/pylint_report.pdf ./lab_06/lab6_full.pdf
          git commit -m "Add generated lab report and Pylint PDF" || echo "No changes to commit"
          git stash --include-untracked
          git pull --rebase origin main
          git stash pop || echo "Nothing to pop"
          git push

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab6-all-pdfs
          path: |
            ./lab_06/lab6.pdf
            ./lab_06/pylint_report.pdf
            ./lab_06/lab6_full.pdf
